# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e537adc1eea861996a2aa747c282cbc13877a2ec9c3289349e894e9df8381747ee42cc3d2194bb82d08cbd5029d37ee256ed8310275b1f291782b489e4c6e679

test:
  secret_key_base: c4b614011c3e7d7f778fb7e7f632aee48130717d1d3f09f5723c4f9772d8a37eecddeeebabb79bca499f4deb656654f0e34a06d8e26b9d8439fdb44280c926e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
